name: CI/CD Workflow

on:
  pull_request:
    branches:
      - develop

env:
  SONAR_ORG: nghiangoclv
  SONAR_PJT: nghiangoclv_nextjs-app

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Run Linting
      - name: Run Lint
        run: yarn lint

  # test:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     # Install dependencies
  #     - name: Install Dependencies
  #       run: yarn install

  #     # Run Tests
  #     - name: Run Tests
  #       run: yarn test

  quality-gate:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectKey=${{ env.SONAR_PJT }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
