name: CI/CD Workflow

on:
  pull_request:
    branches:
      - develop
  
env:
  SONAR_ORG: nghiangoclv
  SONAR_PJT: nghiangoclv_nextjs-app

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   name: Setup Node and Install Dependencies
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Cache and Install Dependencies
  #       run: npm ci
  #     - name: Run ESlint
  #       run: npm run lint 

  # unit-tests:
  #   runs-on: ubuntu-latest

  quality-gate:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectKey=${{ env.SONAR_PJT }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}