name: CI/CD Workflow

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
#   NODE_VERSION: 18.17
  SONAR_ORG: nghiangoclv
  SONAR_PJT: nghiangoclv_nextjs-app
  DOCKER_IMAGE: my-nextjs-app

jobs:
  # testing:
  #   runs-on: ubuntu-latest
  #   name: Setup Node and Install Dependencies
  #   steps:
  #     - name: Setup Cache and Install Dependencies
  #       uses: digi-fry/setup-yarn-node-action@v1
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #     - run: yarn 

  quality-gate:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectKey=${{ env.SONAR_PJT }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: quality-gate
    steps:
      # Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest .

      # Push Docker Image lên Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
