name: CI Workflow

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      
jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint

      - name: Run Test and coverage
        run: yarn jest --coverage

      - name: Run Build
        run: yarn build

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
