name: Trigger Pull Request Staging

on:
    pull_request:
      branches: [staging]

env:
  ENV: STAGING

jobs:
  ut-and-sonar-scanner:
    runs-on: ubuntu-latest
    steps:
    - name: Run Unit Tests and Sonar Scanner
      run: echo "${{ env.ENV }}"
  